FROM python:3.9.1-slim-buster

# set work directory
WORKDIR /usr/src/app

# env variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTBYTECODE 1

# install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip 
RUN pip install -r requirements.txt

# copy project
COPY . .
